name: KArmor
version: 1.0.0
main: me.caarson.karmor.KArmorPlugin
description: Armor system plugin for Bukkit/Paper Minecraft servers.
website: https://github.com/caarson/kArmor
author: caarson

commands:
    carmor:
        description: KArmor root command
        usage: /<command> help
        aliases: [karmor]
        permission: karmor.use
    particles:
        description: Cosmetic armor visuals control
        usage: /carmor particles <subcommand>
        aliases: []
        permission: karmor.cosmetic.use

permissions:
    karmor.use:
        default: true
    karmor.cosmetic.use:
        default: true
    karmor.cosmetic.edit:
        default: op
    karmor.cosmetic.preview:
        default: op
